{{ partial('layouts/blog/blog-first') }}
    <div class="entry-main-blog">

      <!-- por enquanto -->

      <!-- SEGUNDO por enquanto -->

        <div class="all-content">
            <div class="row">
                {% for item_blog in blog %}

                {% set arr = [static_url('assets/img/img_blog/'), item_blog.galeria.imagem] %}
                {% set url = ['blog/post/', item_blog.blog.id] %}
                {% set img = arr|join('') %}
                {% set url_post = url|join('') %}

                <div class="col-md-4 post-single">
                    <a class="link-blog" href="{{ url(url_post) }}">

                        <div class="img-entry">
                            <img src="{{ img }}">
                        </div>

                        <div class="title-content-featured">
                            <p class="subtitle-3">{{ item_blog.blog.titulo }}</p>
                            <p class="text-content-part">
                                {{ strlen(item_blog.blog.conteudo, 200)|striptags }}...<span>Ver mais</span></p>
                                <div class="author-blog list-inline">
                                    <div class="list-inline-item photo-blog">
                                        <img src="{{ static_url('assets/images/user-icon.jpg') }}">
                                    </div>
                                    <div class="list-inline-item photo-blog"><p class="title-3">
                                {% for item_admin in admin_user %}
                                {{ item_admin.administrador.usuario }}
                                {% endfor %}
                            </p>
                        </div>
                        <span class="date-post">{{ item_blog.blog.dt_cad }}</span>
                </div>
            </div>
            </a>
        </div>

        {% endfor %}

     </div>
  </div>


    </div>

{{ partial('layouts/blog/blog-second') }}