<!DOCTYPE html>
<html lang="pt-br">
<head>
    <!--Head -->
    {{ partial('layouts/head') }}
</head>
<body>
<!-- navbar -->
{{ partial('layouts/navbar') }}

<div class="content-inside-post-entry">
    <div class="row">
        <div class="entry-head-blog col-md-12 text-left">
            <h1>Blog Urologia</h1>
        </div>
    </div>
</div>
<div class="content-inside-post-second">


    <div class="init-bar-blog">
        <div class="row">

            <div class="col-md-6">
                <ul class="social-media list-inline">


                    {{ partial('layouts/blog/search') }}

                </ul>
            </div>


            <div class="col-md-6">
                <ul class="paginator list-inline">

                    <li class="list-inline-item"><a class="button-paginator" href="/blog/postpage/{{ previous }}">

                            <img src="{{ static_url('public/assets/img/icon-previous.png') }}">

                        </a></li>
                    <li class="list-inline-item"><a class="button-paginator" href="/blog/postpage/{{ next }}">

                            <img src="{{ static_url('public/assets/img/icon-next.png') }}">

                        </a></li>

                </ul>
            </div>

        </div>




    </div>
    <hr>
</div>