{{ partial('layouts/blog/blog-first') }}
<div class="entry-main-blog">
    <!-- por enquanto -->
    <div class="main-init">
        {% for item_blog_main in blog.items %}
        {% if loop.first %}

        {% set arr = [static_url('assets/img/img_blog/'), item_blog_main.galeria.imagem] %}
        {% set url = ['blog/post/', item_blog_main.blog.id] %}
        {% set img = arr|join('') %}
        {% set url_post = url|join('') %}
        <a class="link-blog" href="{{ url(url_post) }}">
            <div class="row">
                <div class="col-md-8">
                    <div class="img-entry">
                        <img src="{{ img }}">
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="title-content-featured">
                        <p class="subtitle-3">{{ item_blog_main.blog.titulo }}</p>
                        <p class="text-content-part">
                            {{ strlen(item_blog_main.blog.conteudo, 200)|striptags }}...<span>Ver mais</span></p>

                        <div class="author-blog list-inline">
                            <div class="list-inline-item photo-blog">
                                <img src="{{ static_url('public/assets/images/user-icon.jpg') }}">
                            </div>
                            <div class="list-inline-item photo-blog"><p class="title-3">
                                    {% for admin_user_item in admin_user %}
                                    {{ admin_user_item.administrador.usuario }}
                                    {% endfor %}
                                </p>
                            </div>

                            <span class="like" data-post="{{ item_blog.blog.id }}">
                                    <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="heart" class="svg-inline--fa fa-heart fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M462.3 62.6C407.5 15.9 326 24.3 275.7 76.2L256 96.5l-19.7-20.3C186.1 24.3 104.5 15.9 49.7 62.6c-62.8 53.6-66.1 149.8-9.9 207.9l193.5 199.8c12.5 12.9 32.8 12.9 45.3 0l193.5-199.8c56.3-58.1 53-154.3-9.8-207.9z"></path></svg>
                            </span>
                            <span class="amount-like">
                                {{ item_blog.blog.qtd_like }}
                            </span>

                        </div>
                    </div>
                </div>
            </div>
        </a>

        {% endif %}
        {% endfor %}
    </div>



    <!-- SEGUNDO por enquanto -->

    <div class="all-content">
        <div class="row">
            {% for item_blog in blog.items %}
            {% if loop.first == false %}
            {% set arr = [static_url('assets/img/img_blog/'), item_blog.galeria.imagem] %}
            {% set url = ['blog/post/', item_blog.blog.id] %}
            {% set img = arr|join('') %}
            {% set url_post = url|join('') %}

            <div class="col-md-4 post-single">
                <a class="link-blog" href="{{ url(url_post) }}">

                    <div class="img-entry">
                        <img src="{{ img }}">
                    </div>

                    <div class="title-content-featured">
                        <p class="subtitle-3">{{ item_blog.blog.titulo }}</p>
                        <p class="text-content-part">
                            {{ strlen(item_blog.blog.conteudo, 200)|striptags }}...<span>Ver mais</span></p>

                    </div>
                </a>

                <div class="author-blog list-inline">
                    <div class="list-inline-item photo-blog">
                        <img src="{{ static_url('assets/images/user-icon.jpg') }}">
                    </div>
                    <div class="list-inline-item photo-blog"><p class="title-3">
                            {% for item_admin in admin_footer %}
                            {{ item_admin.administrador.usuario }}
                            {% endfor %}
                        </p>
                    </div>
                    <span class="like" data-post="{{ item_blog.blog.id }}">
                                    <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="heart" class="svg-inline--fa fa-heart fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M462.3 62.6C407.5 15.9 326 24.3 275.7 76.2L256 96.5l-19.7-20.3C186.1 24.3 104.5 15.9 49.7 62.6c-62.8 53.6-66.1 149.8-9.9 207.9l193.5 199.8c12.5 12.9 32.8 12.9 45.3 0l193.5-199.8c56.3-58.1 53-154.3-9.8-207.9z"></path></svg>
                    </span>
                    <span class="amount-like">
                                {{ item_blog.blog.qtd_like }}
                    </span>
                </div>
            </div>
            {% endif %}
            {% endfor %}

        </div>
    </div>

</div>


{{ partial('layouts/blog/blog-second') }}