</div>
<div class="content-inside-blog-second">
<hr>
<div class="init-bar-blog">
    <div class="row">

        <div class="col-md-6">

        </div>


        <div class="col-md-6">
            <ul class="paginator list-inline">
                <li class="list-inline-item">Pagina {{ blog.current }} de {{ blog.total_pages }}</li>
                <li class="list-inline-item"><a class="button-paginator" href="/blog/page/{{ blog.first}}">

                        <img src="{{ static_url('public/assets/img/icon-first.png') }}">

                    </a></li>
                <li class="list-inline-item"><a class="button-paginator" href="/blog/page/{{ blog.before}}">

                        <img src="{{ static_url('public/assets/img/icon-previous.png') }}">

                    </a></li>
                <li class="list-inline-item"><a class="button-paginator" href="/blog/page/{{ blog.next}}">

                        <img src="{{ static_url('public/assets/img/icon-next.png') }}">

                    </a></li>
                <li class="list-inline-item"><a class="button-paginator" href="/blog/page/{{ blog.last}}">

                        <img src="{{ static_url('public/assets/img/icon-last.png') }}">

                    </a></li>
            </ul>
        </div>

    </div>




</div>
</div>


{{ partial('layouts/subscribe') }}


<!--footer -->
{{ partial('layouts/footer') }}
</body>
</html>
