<?php
/**
 * Created by PhpStorm.
 * User: georgericardo
 * Date: 24/06/19
 * Time: 13:33
 */
use ControllerBase\ControllerBase;
use Phalcon\Forms\Form;
use Phalcon\Mvc\View;
use Phalcon\Paginator\Factory;
use Phalcon\Paginator\Adapter\Model as PaginatorModel;
class ContatoController extends ControllerBase
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->view->setTemplateAfter('contato');

    }

    public function indexAction()
    {
        $this->view->setRenderLevel(View::LEVEL_LAYOUT);
        $this->view->setLayout("contato");
    }

    /**
     * @throws \Exception
     */
    public function formAction()
    {

      $message = new Mensagem();
        // Store and check for errors
        $success = $message->save(
            $this->request->getPost(),
            array('name', 'subject', 'email', 'msg', 'status')
        );
        // passing the result to the view
        $this->view->sucess = $success;
        if ($success) {
            $this->response->redirect("/contato");
            $this->flash->success("Dados inseridos com sucesso!");
        } else {
            $this->response->redirect("/contato");
            // $message = "Sorry, the following problems were generated:<br>" . implode('<br>', $users->getMessages());
            $this->flash->error("erro ao inserir contato");
            $this->view->message = $message->getMessages();
        }

        //$this->response->redirect("/contato");
       /*$this->dispatcher->forward(
            [
                'controller' => 'contato',
                'action'     => 'contato'
            ]
        );*/
        // passing a message to the view
        //$this->view->message = $message;


      /* $form = new Form();
       $contact = new Mensagem();
       $data = $this->request->getPost();

          if($form->isValid($data, $contact)) {
              $result = $contact->save($data,
                  ['name', 'subject', 'email', 'msg', 'status']);
              $this->view->sucess = $result;
            if (!$result){
                $this->flash->error("Infelizmente aconteceu um problema, tente novamente mais tarde.");
            }
            else {
                $this->flash->success("E-mail enviado com sucesso!");
            }

        }
        else {

            $this->flash->error("Infelizmente aconteceu um problema, tente novamente mais tarde.");
        }

        $this->dispatcher->forward(["action" => "index"]);
        $form->clear();*/

    }


    public function contatoAction()
    {
        $this->view->setRenderLevel(View::LEVEL_LAYOUT);
        $this->view->setLayout("contato");
    }

}