<?php
/**
 * Created by PhpStorm.
 * User: georgericardo
 * Date: 11/06/19
 * Time: 22:01
 */
use Phalcon\Mvc\Model;
class Duvidas extends Model
{
    public $id;
    public $pergunta;
    public $resposta;
    public $dt_cad;

    public function initialize()
    {
        $this->setSource('perguntas_frequentes');
    }

    protected function setSource($source)
    {
        parent::setSource($source); // TODO: Change the autogenerated stub
    }

}