<!DOCTYPE html>
<html lang="pt-br">
<head>
    <!--Head -->
    {{ partial('layouts/head') }}
</head>
<body>
<!-- navbar -->
{{ partial('layouts/navbar') }}



<div class="entry content-inside-blog-5">
    <div class="row">
        <div class="col-md-6 section-question-us text-center">
            <h1 class="title-about-us">Contato</h1>
            <p class="subtitle-about-us"></p>

        </div>

        <div class="col-md-6 section-about-us-image text-center">
            <div class="contact-img">
                {{ image(static_url('assets/images/contact-icon.png'), 'alt': 'contato') }}
            </div>
        </div>
    </div>

</div>


<div class="content-inside-blog">

    <h1 class="title-1">Entre em contato conosco</h1>
    <p class="subtitle-1">Ficaremos muito felizes de receber seu contato.</p>

    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="form-contact">

                    {{ form('contato/form', 'method': 'post') }}
                    <label for="name">Nome:</label>
                    {{ text_field('name', 'class': 'form-control form-contact-input') }}
                    <br>
                    <label for="subject">Assunto:</label>
                    {{ text_field('subject', 'class': 'form-control form-contact-input') }}
                    <br>
                    <label for="email">E-mail:</label>
                    {{ text_field('email', 'class': 'form-control form-contact-input') }}
                    <br>
                    <label for="msg">Mensagem:</label>
                    {{ text_area('msg', 'rows': 6, 'class': 'form-control form-contact-input') }}
                    <br>
                    {{ hidden_field('status', 'value': '1') }}
                    {{ submit_button('Search', 'class': 'btn btn-primary', 'value': 'Enviar') }}
                    {{ endForm() }}

                </div>
                {{ sucess }}
            </div>

            <div class="col-md-6 section-about-us-image">
                <div class="image-about-us">
                    {{ image(static_url('assets/images/back-office-services.png'), 'alt': 'consultorio') }}
                </div>
            </div>

        </div>
    </div>

</div>
<div id="map"></div>
{{ partial('layouts/subscribe') }}
<!--footer -->
{{ partial('layouts/footer') }}

</body>
</html>
