<!DOCTYPE html>
<html lang="pt-br">
<head>
    <!--Head -->
    {{ partial('layouts/head') }}
</head>
<body>
<!-- navbar -->
{{ partial('layouts/navbar') }}




<div class="entry content-inside-question">
    <div class="row">
        <div class="col-md-6 section-question-us text-center">
            <h1 class="title-about-us">Dúvidas <span>Frequentes</span></h1>
            <p class="subtitle-about-us">Saiba quais são as dúvidas mais frequentes.</p>

        </div>

        <div class="col-md-6 section-about-us-image">
            <div class="images-questions">
                <div class="image-question-1">
                    {{ image(static_url('assets/images/questions-1.png'), 'class': 'image-1') }}
                </div>

                <div class="image-question-2">
                    {{ image(static_url('assets/images/questions-2.png'), 'class': 'image-2') }}
                </div>

                <div class="image-question-3">
                    {{ image(static_url('assets/images/questions-3.png'), 'class': 'image-3') }}
                </div>
            </div>
        </div>
    </div>

</div>

<div class="content-inside-blog">

    <h1 class="title-1">Perguntas Recentes</h1>
    <p class="subtitle-1">Veja as principais perguntas feitas por leitores.</p>

    {% for item_duvidas in duvidas %}

    <div class="sub-content-blog questions">
        <div class="ask-blog">
            <div class="row">
                <div class="col-md-2">
                    <div class="ask-blog-part1">

                    </div>
                </div>

                <div class="col-md-8 text-center">
                    <div class="ask-blog-part2">
                        <h1 class="title-2">{{ item_duvidas.pergunta }}</h1>
                    </div>
                    <a class="btn btn-primary btn-custom-ask wow fadeInUp" data-wow-delay="1100ms" href="javascript:void(0)">VEJA A RESPOSTA</a>

                </div>

                <div class="col-md-2">
                    <div class="ask-blog-part3">

                    </div>
                </div>


            </div>
        </div>
        <div class="answer">
            <p>{{ item_duvidas.resposta }}</p>
        </div>
    </div>

    {% endfor %}

</div>





{{ partial('layouts/subscribe') }}
<!--footer -->
{{ partial('layouts/footer') }}
</body>
</html>
