
<div class="plugin">
    <div class="content-plugin">
        <div class="cover">
            Marque sua consulta pelo whatsapp.
        </div>

        <div class="inside">

            <p>(85) 98122-4161</p>

        </div>
    </div>
</div>

<div class="footer-blog">
    <div class="w3-container footer-inside">
        <div class="w3-row">
            <div class="w3-col l3 s12">
                <h2 class="title-5">
                    Informações Importantes
                </h2>
                <ul class="options-footer">

                    {% for admin_user_item in admin_footer %}

                    <li><p class="link-footer">{{ admin_user_item.administrador.endereco }}</p> </li>
                    <li>
                        <p class="link-footer">{{ admin_user_item.administrador.telefone_pri }} - {{ admin_user_item.administrador.telefone_sec }}</p>

                    </li>

                    {% endfor %}
                </ul>
            </div>



            <div class="w3-col l2 s12">
                <h2 class="title-5">
                    Geral
                </h2>
                <ul class="options-footer">
                    <li><a class="link-footer" href="/jeronimo">Jeronimo Coelho</a> </li>
                    <li><a class="link-footer" href="/servicos">Servicos</a></li>
                    <li><a class="link-footer" href="/blog">Blog</a></li>
                    <li><a class="link-footer" href="/duvidas">Duvidas Frequentes</a></li>
                    <li><a class="link-footer" href="/contato">Contato</a></li>
                </ul>
            </div>

            <div class="w3-col l4 s12">
                <h2 class="title-5">
                    Links Importantes
                </h2>
                <ul class="options-footer">
                    <li><a class="link-footer" href="http://www.auanet.org/" target="_blank">American Urological Association</a> </li>
                    <li><a class="link-footer" href="http://www.europeanurology.com/" target="_blank">European Association of Urology</a></li>
                    <li><a class="link-footer" href="http://www.uroweb.org/" target="_blank">European Urology Jornal</a></li>
                    <li><a class="link-footer" href="http://www.sbu.org.br/" target="_blank">Sociedade Brasileira de Urologia</a></li>
                    <li><a class="link-footer" href="http://www.sbu-sp.org.br/" target="_blank">Sociedade Brasileira de Urologia – Seção São Paulo</a></li>

                    <li><a class="link-footer" href="http://www.issm.info/" target="_blank">Sociedade Internacional de Medicina Sexual</a> </li>
                    <li><a class="link-footer" href="http://www.urologista.com.br/www.slamsnet.org" target="_blank">Sociedade Latino-Americana de Medicina Sexual</a></li>
                    <li><a class="link-footer" href="http://www.slamsnet.org/pt">Sociedade Latino-Americana de Medicina Sexual</a></li>
                    <li><a class="link-footer" href="http://www.siu-urology.org/" target="_blank">Société Internationale d’Urologie</a></li>
                    <li><a class="link-footer" href="http://www.baus.org.uk/" target="_blank">The British Association of Urological Surgeons</a></li>

                    <li><a class="link-footer" href="http://www.urologyhealth.org/" target="_blank">Urology Care Foundation</a></li>
                    <li><a class="link-footer" href="http://urologytimes.modernmedicine.com/" target="_blank">Urology Times</a></li>
                </ul>
            </div>



            <div class="w3-col l3 s12">
                <img class="logo-footer" src="{{ static_url('assets/images/logo_mini.png') }}">
                <p class="link-footer-logo">&copy; 2019 <b>Jeronimo Coelho</b>.<br>Todos os direitos reservados.<p></p>
            </div>
        </div>
    </div>
</div>

{{ assets.outputJs('footer') }}
{{ javascript_include('public/assets/js/jssor.slider.min.js', true) }}
{{ javascript_include('public/assets/js/slider.js', true) }}
{{ javascript_include('public/assets/js/slide-rate.js', true) }}
{{ javascript_include('public/assets/js/questions.js', true) }}
{{ javascript_include('public/assets/js/moment.js', true) }}
{{ javascript_include('public/assets/js/handDate.js', true) }}
{{ javascript_include('public/assets/js/smartphoto.js', true) }}
{{ javascript_include('public/assets/js/base.js', true) }}
<!--{{ javascript_include('http://maps.googleapis.com/maps/api/js?key=AIzaSyDHQQJXaGAMJgvpXBFM_Hcv_1-Geg0o1UE&amp;sensor=false') }} -->

{{ javascript_include('public/assets/js/map.js', true) }}
{{ javascript_include('https://maps.googleapis.com/maps/api/js?key=AIzaSyDHQQJXaGAMJgvpXBFM_Hcv_1-Geg0o1UE&callback=initMap', false) }}







