<!DOCTYPE html>
<html lang="en">
<head>
    <!--Head -->
    {{ partial('layouts/head') }}
</head>
<body>
<!-- navbar -->
{{ partial('layouts/navbar') }}

<div class="entry content-inside-blog-3">
    <div class="row">
        <div class="col-md-6 section-about-us text-center">
            <h1 class="title-about-us">Saiba os nossos <span>Serviços prestados</span></h1>
            <p class="subtitle-about-us">Veja todos os nossos serviços.</p>

        </div>

        <div class="col-md-6 section-about-us-image">
            <div class="image-about-us">
                <img src='{{ static_url('assets/images/back-office-services.png') }}'>
            </div>
        </div>
    </div>

</div>
<div class="entry content-inside-blog-4">
    <div class="about-us-qualify">
        <h1 class="title-1">Serviços</h1>
    </div>


    <div class="qualifications-text">
        <div class="row inside-services">
            <div class="col-md-6">

                {% set count = 0 %}

                {% for index, item_serv1 in services1 %}

                <div class="tab-services">
                    <div class="number-service">
                        <span>&#10004;</span>
                    </div>
                    <div class="content-service">
                        {{ item_serv1.servico }}
                    </div>
                </div>

                {% endfor %}

            </div>


            <div class="col-md-6">

                {% for index, item_serv2 in services2 %}

                <div class="tab-services">
                    <div class="number-service">
                        <span>&#10004;</span>
                    </div>
                    <div class="content-service">
                        {{ item_serv2.servico }}
                    </div>
                </div>

                {% endfor %}

            </div>
        </div>
    </div>
</div>

<div class="content-inside-blog-3">
    {{ partial('layouts/photos_office') }}
</div>

<!-- blog resume -->
{{ partial('layouts/resume_blog') }}


<!--footer -->
{{ partial('layouts/footer') }}
</body>
</html>
